-- noodles

CREATE TABLE noodles (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	title TEXT,
	recommendations TEXT
);

CREATE TABLE diet (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	title TEXT,
	description TEXT
);

INSERT INTO noodles (title,recommendations) VALUES
	('tortellini', 'cook to al dente'),
	('risotto', 'sauce'),
	('elbow macaroni', 'add some cheese'),
	('cavatelli', 'with braised lamb and fresh ricotta');

INSERT INTO diet (title, description) VALUES
	('vegetarian', 'contains no meat'),
	('vegan', 'contains no animal products'),
	('gluten free', 'contains no gluten'),
	('lactose free', 'safe for people who cannot eat dairy');
	
CREATE TABLE noodles_diets(
	noodle_id INTEGER REFERENCES noodles(id) NOT NULL,
	diet_id INTEGER REFERENCES diet(id) NOT NULL,
	PRIMARY KEY(noodle_id, diet_id)
);

INSERT INTO noodles_diets(noodle_id, diet_id) VALUES
	(1, 1),
	(2, 1),
	(2, 2),
	(2, 3),
	(2, 4),
	(3, 1);

SELECT * FROM noodles
	JOIN noodles_diets ON noodles.id = noodles_diets.noodle_id
	JOIN diet ON noodles_diets.diet_id = diet.id
	WHERE noodles.title = 'elbow macaroni';

